Rems 326 mongoose etasu
mcode/REMS pull request #59
Opened 2023-03-27 18:43 UTC by kennyEung

## Describe your changes

Please include a summary of the changes and the related issue/task. Please also include relevant motivation and context. List any dependencies that are required for this change, including links to other pull requests/branches in other repositories if applicable.

## Issue ticket number and Jira link

Please include the Jira Ticket Number and Link for this issue/task.

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] Ensure the target / base branch for any feature PR is set to `dev` not main (the only exception to this is releases from `dev` and hotfix branches)

## Checklist for conducting a review
- [ ] Review the code changes and make sure they all make sense and are necessary. 
- [ ] Pull the PR branch locally and test by running through workflow and making sure everything works as it is supposed to. 

## Workflow 

Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled below if additional changes are likely not to be needed. The bot will auto assign reviewers to your Pull Request for you.

2023-03-27 19:30 UTC, smalho01 commented
looks good, but is missing the mongoose api calls, will rearview once those are in

2023-03-27 20:50 UTC, smalho01 requested changes

2023-03-27 20:50 UTC, smalho01 commented on src/fhir/utilities.ts
>      const medicationCollection = await db.collection(
this is the old mongo api

2023-03-28 21:41 UTC, plarocque4 approved these changes

2023-03-28 21:41 UTC, merged